### ISSUE TITLE
[BUG] error calling markdownify: text is already rendered

### ISSUE THREAD

**Issue by Thanatermesis** [pacollins/calligraphy#1]
I'm trying to use this beautiful theme, to try it I add a copy of the themes dir on exampleSite and then I run "hugo server", after that complains about a markup file that I need to delete first, it finally renders the site beautifully

Unfortunately, as a difference from the demo site, the TOC card (and author card in the other sidebar) doesn't automatically appears when scrolling down a demo page, is this a bug?

**Comment by pacollins** [comment]
Are your posts under the "blog" directory or something else?

**Comment by Thanatermesis** [comment]
I was just trying the template because I liked it, but I was not able to successfully implement it because of that, what I mean is that the contents I have used are all the ones from the "exampleSite" directory, I tried to run hugo from it to play a little with the template before to implement it (note that if you try that, seems like is needed to delete a file from a markup directory because of an error that shows up, not sure if this is related to the issue)

**Comment by pacollins** [comment]
Can you post the error?

The demo site builds from `exampleSite` and does not have an error. 

Would you also mind running `hugo verson` to ensure your are running extended?

**Comment by Thanatermesis** [comment]
Yes, extended last version of Hugo

Error:
`Error: Error building site: "/home/pruebas/testsite/themes/calligraphy/exampleSite/themes/calligraphy/layouts/_default/_markup/render-image.html:40:96": execute of template failed: template: _default/_markup/render-image.html:40:96: executing "_default/_markup/render-image.html" at <markdownify>: error calling markdownify: text is already rendered, repeating it may cause infinite recursion`

Full demo of the issue: 

[![asciicast](https://asciinema.org/a/486813.svg)](https://asciinema.org/a/486813)

**Comment by Thanatermesis** [comment]
Seems like the TOC auto-appearing shows up now, my issue was in a different machine where I tried to reproduce it here

The only issue remaining is the error message included in the previous post, which I'm not sure how much relevant it is, but since the TOC does appear now, the issue can be closed :)

**Comment by pacollins** [comment]
Never seen that one before, but I have had issue with that template so I need to adjust it. I'll leave this open until I can investigate further - thanks for pointing it out!

**Comment by Thanatermesis** [comment]
Thank you, I think for reproducing the issue you can try the same steps showing in the cast which takes literally 1 minute :) if you still not be able to reproduce that error another suggestion is to simply download Elive and run it in Live mode where you can do all the same steps using the same OS where it happens.

**Comment by Damon-V79** [comment]
Hello, I have the same error with hugo_extended v0.97.0, v0.96.0, v0.95.0. But do not have this error with hugo_extended v0.90.1.

**Comment by pacollins** [comment]
Thanks @Damon-V79 - I'm going to update to the latest version of Hugo to see if I can reproduce and hopefully patch it!

**Comment by pacollins** [comment]
As part of [Hugo v0.94.0](https://github.com/gohugoio/hugo/releases/tag/v0.94.0):

> We now fail with error when double-rendering text in markdownify/RenderString https://github.com/gohugoio/hugo/commit/4e14cf7607ad3afdbf65272cd5bb61dba4b415da @bep https://github.com/gohugoio/hugo/pull/9570 https://github.com/gohugoio/hugo/issues/8959

Creating a PR now. Thanks @Thanatermesis and @Damon-V79 for the information!
