### ISSUE TITLE
Error while deploying 

### ISSUE THREAD

**Issue by njts** [pacollins/calligraphy#10]
Start building sites …
hugo v0.92.2+extended linux/amd64 BuildDate=2022-02-23T16:47:50Z VendorInfo=ubuntu:0.92.2-1
ERROR 2022/07/15 03:45:34 render of "taxonomy" failed: "/root/nijatoes/themes/calligraphy/layouts/_default/baseof.html:53:21": execute of template failed: template: authors/terms.html:53:21: executing "authors/terms.html"
at <$image.Fit>: nil pointer evaluating resource.Resource.Fit
ERROR 2022/07/15 03:45:34 render of "taxonomy" failed: "/root/nijatoes/themes/calligraphy/layouts/_default/baseof.html:53:21": execute of template failed: template: series/taxonomy.html:53:21: executing "series/taxonomy.html" at <$image.Fit>: nil pointer evaluating resource.Resource.Fit
ERROR 2022/07/15 03:45:34 render of "taxonomy" failed: "/root/nijatoes/themes/calligraphy/layouts/_default/baseof.html:53:21": execute of template failed: template: _default/taxonomy.html:53:21: executing "_default/taxonomy.html" at <$image.Fit>: nil pointer evaluating resource.Resource.Fit
ERROR 2022/07/15 03:45:34 render of "taxonomy" failed: "/root/nijatoes/themes/calligraphy/layouts/_default/baseof.html:53:21": execute of template failed: template: _default/taxonomy.html:53:21: executing "_default/taxonomy.html" at <$image.Fit>: nil pointer evaluating resource.Resource.Fit
Error: Error building site: failed to render pages: render of "home" failed: "/root/nijatoes/themes/calligraphy/layouts/_default/baseof.html:53:21": execute of template failed: template: _default/list.html:53:21: executing "_default/list.html" at <$image.Fit>: nil pointer evaluating resource.Resource.Fit
Built in 28 ms

**Comment by pacollins** [comment]
Without seeing the repo, it looks like you are missing the author headshot or it is in the wrong location. It should default to the guest author image unless you deleted that.
