### ISSUE TITLE
How to increase the size of the main container?

### ISSUE THREAD

**Issue by Thanatermesis** [pacollins/calligraphy#2]
I like this template and thinking to use it for my blog, but I found the main container to be a bit small in width, I tried to modify the theme without success, like "main-container" in the _mixins.scss file.

It looks like the right and left limits are limited by the main container size? would make more sense if the left and right column (just like the main container) will fill the empty spaces in the left and right in order to resize the contents to the browsers dimensions, not sure if I'm explaining correctly but there's an example of these "empty spaces" 

![image](https://user-images.githubusercontent.com/1181626/163105808-c0d698f3-bd39-487b-8bf2-f2c4307e96ff.png)

**Comment by pacollins** [comment]
The container width is set based on [optimal line length](https://baymard.com/blog/line-length-readability) and is not currently adjustable. Filling the screen will actually lead to UX problems on larger screens without being careful. At this point, I have no plans to change this on the theme.

In the future, please use the [discussions](https://github.com/pacollins/calligraphy/discussions) tab for questions to keep issues reserved for verified issues or feature requestions.
