### ISSUE TITLE
Google fonts not being displayed

### ISSUE THREAD

**Issue by algoexpt** [pacollins/calligraphy#6]
Because of the way the scss is generated, the @import statement is appearing somewhere in the middle, after the normalize and toc imports.

Moving the @import of googlefonts to the first line (in the browser developer tools) fixes this, we do see the Google fonts correctly.

My gut feeling is this is to do with the sequence in which the scss file is generated (not sure, not a front end developer).

Can you please take a look and make a fix? 

I love your theme!
![Screenshot_20220702_003858](https://user-images.githubusercontent.com/22828481/176926509-6dec6345-44c0-4bc8-8c0d-f1f5514199d2.png) 

Font is not displayed because first line is not the import from google fonts

![Screenshot_20220702_003925](https://user-images.githubusercontent.com/22828481/176926591-e80b9877-99d8-40dd-9c74-e1d051e8ca22.png)

Font displayed correctly when import from google fonts is the first line

**Comment by pacollins** [comment]
I will look into this, but I think you are right. I bet I didn't notice
when I made changes because it was cached. I'll try to patch that today.

**Comment by pacollins** [comment]
@algoexpt - If you would be so kind as to check the PR, I'll go ahead and merge! I took the opportunity to also include font files into the theme for those who prefer to not use CDNs.

**Comment by algoexpt** [comment]
Checked, and it works! Good idea to include font files in static as well. Thanks!

**Comment by algoexpt** [comment]
I'll reopen, you can close after you merge the PR
